- name: Exécuter Jenkins dans Docker
  docker_container:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ jenkins_port }}:8080"
    volumes:
      - "{{ jenkins_home }}:/var/jenkins_home"
      - "{{ playbook_dir }}/files/:/usr/share/jenkins/ref/init.groovy.d/"
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"