- name: Install Docker SDK for Python
  pip:
    name: docker

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: yes
    
- name: Exécuter Nexus dans Docker
  docker_container:
    name: "{{ nexus_container_name }}"
    image: "{{ nexus_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ nexus_port }}:8081"
    volumes:
      - "{{ nexus_home }}:/opt/sonatype/nexus3"
    env:
      NEXUS_SECURITY_RANDOMPASSWORD: "false"
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:MaxDirectMemorySize=512m"  # Adjusted Java heap settings
    memory: "2g"