- name: Pre-install requirements
  hosts: localhost
  become: yes
  roles:
    - pre

- name: Install DevOps Stack
  hosts: localhost
  become: yes
  roles:
    - bdd
    - sonar
    - nexus
    - jenkins