version: "3.8"

services:
  mariadb_sonarqube:
    image: mariadb:latest
    container_name: mariadb_sonarqube
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sonarqube
      MYSQL_USER: integ
      MYSQL_PASSWORD: integ
    volumes:
      - sonarqube_db_data:/var/lib/mysql
    ports:
      - "3307:3306" # Expose port 3306 for mariadb_sonarqube

  mariadb_other:
    image: mariadb:latest
    container_name: mariadb_other
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otherroot
      MYSQL_DATABASE: otherdb
      MYSQL_USER: otheruser
      MYSQL_PASSWORD: otherpass
    volumes:
      - other_db_data:/var/lib/mysql
    ports:
      - "3308:3306" # Expose port 3307 for mariadb_other

volumes:
  sonarqube_db_data:
  other_db_data:
