version: "3.8"

services:
  postgres_sonarqube:
    image: postgres:latest
    container_name: postgres_sonarqube
    restart: always
    environment:
      POSTGRES_USER: integ
      POSTGRES_PASSWORD: integ
      POSTGRES_DB: sonarqube
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_sonarqube:
