Vagrant.configure("2") do |config|
  # Définir la version de la box et le nom de la machine
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "ansible-vm"

  # Configurer la mémoire RAM et l'espace disque de la machine virtuelle
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6072" 
  end

  config.vm.network "forwarded_port", guest: 22, host: 2222 
  config.vm.network "forwarded_port", guest: 8080, host: 8080 
  config.vm.network "forwarded_port", guest: 8081, host: 8081 
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 3307, host: 3307
  config.vm.network "forwarded_port", guest: 3308, host: 3308

  # Provisionnement pour copier la clé publique dans la VM
  # config.vm.provision "file", source: "../keys/insecure_private_key.pub", destination: "/home/vagrant/.ssh/authorized_keys"
  # config.vm.provision "file", source: "../keys/insecure_private_key", destination: "/home/vagrant/insecure_private_key"

  # Provisionning playbook file
  config.vm.provision "file", source: "./provisioning", destination: "/home/vagrant/provisioning"

  # Provisioning : mettre à jour le gestionnaire de packages et installer les outils de base
  config.vm.provision "shell", inline: <<-SHELL
    echo "--- Début du provisioning Shell ---"
    echo "Mise à jour des paquets..."
    apt-get update -y && apt-get upgrade -y

    echo "Installation des outils nécessaires..."
    apt-get install -y sudo curl vim unzip htop software-properties-common

    echo "🧹 Suppression d'Ansible installé via APT (si présent)..."
    apt-get remove -y ansible || true

    echo "📦 Installation des dépendances Python..."
    apt-get install -y python3 python3-pip python3-dev build-essential

    echo "⬆️ Mise à jour de pip et installation de la dernière version d'Ansible..."
    pip3 install --upgrade pip
    pip3 install ansible

    echo "✅ Ansible installé avec succès ! Version :"
    ansible --version

    echo "--- Fin du provisioning Shell ---"
  SHELL

  # Exécution automatique du playbook Ansible après l'installation
  config.vm.provision "shell", inline: <<-SHELL
    echo "--- Exécution du playbook Ansible ---"
    ansible-playbook /home/vagrant/provisioning/playbook.yml -i "localhost," --connection=local
    echo "--- Fin de l'exécution du playbook ---"
  SHELL

end
